<?php
require_once 'includes/auth.php';
requireLogin();

$user = currentUser();
$hoje = date('Y-m-d');

// KPI: reservations today
$stmt = $conn->prepare("SELECT COUNT(*) AS total FROM reservas WHERE data_reserva = ? AND status != 'cancelada'");
if (!$stmt) die('SQL error (reservas hoje): ' . $conn->error);
$stmt->bind_param('s', $hoje);
$stmt->execute();
$reservasHoje = $stmt->get_result()->fetch_assoc()['total'];
$stmt->close();

// KPI: active rooms
$r = $conn->query("SELECT COUNT(*) AS total FROM salas WHERE status = 'ativa'");
if (!$r) die('SQL error (salas ativas): ' . $conn->error);
$salasAtivas = $r->fetch_assoc()['total'];

// KPI: active users
$r = $conn->query("SELECT COUNT(*) AS total FROM usuarios WHERE ativo = 1");
if (!$r) die('SQL error (users ativos): ' . $conn->error);
$usersAtivos = $r->fetch_assoc()['total'];

// KPI: pending reservations
$stmt = $conn->prepare("SELECT COUNT(*) AS total FROM reservas WHERE status = 'pendente' AND data_reserva >= ?");
if (!$stmt) die('SQL error (pendentes): ' . $conn->error);
$stmt->bind_param('s', $hoje);
$stmt->execute();
$pendentes = $stmt->get_result()->fetch_assoc()['total'];
$stmt->close();

// Normal reservations (not generated by recurrence), today and future, max 10
$stmt = $conn->prepare("
    SELECT r.data_reserva, r.hora_inicio, r.hora_fim, r.assunto, r.status,
           s.nome AS sala_nome, u.nome AS usuario_nome
    FROM reservas r
    JOIN salas s ON s.id = r.sala_id
    JOIN usuarios u ON u.id = r.usuario_id
    WHERE r.data_reserva >= ? AND r.status != 'cancelada' AND r.recorrencia_id IS NULL
    ORDER BY r.data_reserva ASC, r.hora_inicio ASC
    LIMIT 10
");
if (!$stmt) die('SQL error (normais): ' . $conn->error);
$stmt->bind_param('s', $hoje);
$stmt->execute();
$normais = $stmt->get_result();
$stmt->close();

// Active recurring rules
$recorrencias = $conn->query("
    SELECT rc.assunto, rc.tipo, rc.dia_semana, rc.dia_mes, rc.hora_inicio, rc.hora_fim, rc.ativa,
           s.nome AS sala_nome, u.nome AS usuario_nome
    FROM recorrencias rc
    JOIN salas s ON s.id = rc.sala_id
    JOIN usuarios u ON u.id = rc.usuario_id
    WHERE rc.ativa = 1
    ORDER BY rc.tipo ASC, rc.dia_semana ASC
");
if (!$recorrencias) die('SQL error (recorrencias): ' . $conn->error);

$page_title = "Dashboard";
require_once 'includes/header.php';
require_once 'includes/sidebar.php';
?>

<!-- Main Content -->
<div class="main-content">
    <!-- Header -->
    <div class="header d-flex justify-content-between align-items-center">
        <div>
            <button class="btn btn-outline-secondary d-md-none me-3" id="sidebarToggle">
                <i class="bi bi-list"></i>
            </button>
            <h4 class="mb-0">Dashboard</h4>
            <small class="text-muted">Visão geral do sistema</small>
        </div>
        <div class="dropdown">
            <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                <i class="bi bi-person-circle me-1"></i>
                <?php echo htmlspecialchars($user['nome']); ?>
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#"><i class="bi bi-person me-2"></i>Perfil</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="logout.php"><i class="bi bi-box-arrow-right me-2"></i>Sair</a></li>
            </ul>
        </div>
    </div>

    <!-- Content -->
    <div class="container-fluid px-4">
        <?php renderFlash(); ?>

        <!-- Stats Cards -->
        <div class="row mb-4">
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="stat-card">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <div class="text-muted small">Reservas Hoje</div>
                            <div class="h4 mb-0"><?php echo $reservasHoje; ?></div>
                        </div>
                        <div class="stat-icon">
                            <i class="bi bi-calendar-day"></i>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="stat-card">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <div class="text-muted small">Salas Ativas</div>
                            <div class="h4 mb-0"><?php echo $salasAtivas; ?></div>
                        </div>
                        <div class="stat-icon">
                            <i class="bi bi-door-open"></i>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="stat-card">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <div class="text-muted small">Usuários Ativos</div>
                            <div class="h4 mb-0"><?php echo $usersAtivos; ?></div>
                        </div>
                        <div class="stat-icon">
                            <i class="bi bi-people"></i>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="stat-card">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <div class="text-muted small">Reservas Pendentes</div>
                            <div class="h4 mb-0"><?php echo $pendentes; ?></div>
                        </div>
                        <div class="stat-icon">
                            <i class="bi bi-clock-history"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Quick Actions & Recent Bookings -->
        <div class="row">
            <div class="col-lg-4 mb-4">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Ações Rápidas</h5>
                    </div>
                    <div class="card-body">
                        <div class="d-grid gap-2">
                            <a href="nova_reserva.php" class="btn btn-primary">
                                <i class="bi bi-plus-circle me-2"></i>Nova Reserva
                            </a>
                            <a href="salas.php" class="btn btn-outline-primary">
                                <i class="bi bi-door-open me-2"></i>Gerir Salas
                            </a>
                            <?php if ($user['perfil'] === 'admin'): ?>
                            <a href="usuarios.php" class="btn btn-outline-primary">
                                <i class="bi bi-people me-2"></i>Gerir Usuários
                            </a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-lg-8 mb-4">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="card-title mb-0"><i class="bi bi-calendar-event me-2"></i>Reservas Normais</h5>
                        <a href="reservas.php" class="btn btn-sm btn-outline-primary">Ver Todas</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Sala</th>
                                        <th>Data</th>
                                        <th>Horário</th>
                                        <th>Assunto</th>
                                        <th>Responsável</th>
                                        <th>Estado</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if ($normais->num_rows === 0): ?>
                                        <tr><td colspan="6" class="text-center text-muted">Sem reservas normais futuras</td></tr>
                                    <?php else: ?>
                                        <?php while ($row = $normais->fetch_assoc()): ?>
                                        <tr>
                                            <td><?php echo htmlspecialchars($row['sala_nome']); ?></td>
                                            <td><?php echo date('d/m/Y', strtotime($row['data_reserva'])); ?></td>
                                            <td><?php echo substr($row['hora_inicio'], 0, 5) . ' - ' . substr($row['hora_fim'], 0, 5); ?></td>
                                            <td><?php echo htmlspecialchars($row['assunto']); ?></td>
                                            <td><?php echo htmlspecialchars($row['usuario_nome']); ?></td>
                                            <td>
                                                <?php
                                                $badge = match($row['status']) {
                                                    'confirmada' => 'bg-success',
                                                    'pendente'   => 'bg-warning',
                                                    'cancelada'  => 'bg-danger',
                                                    default      => 'bg-secondary',
                                                };
                                                ?>
                                                <span class="badge <?php echo $badge; ?>"><?php echo ucfirst($row['status']); ?></span>
                                            </td>
                                        </tr>
                                        <?php endwhile; ?>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Recurring Reservations -->
        <div class="row">
            <div class="col-12 mb-4">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="card-title mb-0"><i class="bi bi-arrow-repeat me-2"></i>Reservas Recorrentes</h5>
                        <a href="recorrencias.php" class="btn btn-sm btn-outline-primary">Ver Todas</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Sala</th>
                                        <th>Frequência</th>
                                        <th>Dia</th>
                                        <th>Horário</th>
                                        <th>Assunto</th>
                                        <th>Responsável</th>
                                        <th>Estado</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if ($recorrencias->num_rows === 0): ?>
                                        <tr><td colspan="7" class="text-center text-muted">Sem recorrências ativas</td></tr>
                                    <?php else: ?>
                                        <?php
                                        $diasSemana = ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'];
                                        while ($rc = $recorrencias->fetch_assoc()):
                                            $dia = $rc['tipo'] === 'semanal'
                                                ? ($diasSemana[(int)$rc['dia_semana']] ?? '-')
                                                : 'Dia ' . (int)$rc['dia_mes'];
                                        ?>
                                        <tr>
                                            <td><?php echo htmlspecialchars($rc['sala_nome']); ?></td>
                                            <td><span class="badge bg-info"><?php echo ucfirst($rc['tipo']); ?></span></td>
                                            <td><?php echo $dia; ?></td>
                                            <td><?php echo substr($rc['hora_inicio'], 0, 5) . ' - ' . substr($rc['hora_fim'], 0, 5); ?></td>
                                            <td><?php echo htmlspecialchars($rc['assunto']); ?></td>
                                            <td><?php echo htmlspecialchars($rc['usuario_nome']); ?></td>
                                            <td><span class="badge bg-success">Ativa</span></td>
                                        </tr>
                                        <?php endwhile; ?>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require_once 'includes/footer.php'; ?>