<?php
require_once 'includes/auth.php';
requireLogin();

$user = currentUser();
$hoje = date('Y-m-d');

// KPI: reservations today
$stmt = $conn->prepare("SELECT COUNT(*) AS total FROM reservas WHERE data_reserva = ? AND status != 'cancelada'");
if (!$stmt) die('SQL error (reservas hoje): ' . $conn->error);
$stmt->bind_param('s', $hoje);
$stmt->execute();
$reservasHoje = $stmt->get_result()->fetch_assoc()['total'];
$stmt->close();

// KPI: active rooms
$r = $conn->query("SELECT COUNT(*) AS total FROM salas WHERE status = 'ativa'");
if (!$r) die('SQL error (salas ativas): ' . $conn->error);
$salasAtivas = $r->fetch_assoc()['total'];

// KPI: active users
$r = $conn->query("SELECT COUNT(*) AS total FROM usuarios WHERE ativo = 1");
if (!$r) die('SQL error (users ativos): ' . $conn->error);
$usersAtivos = $r->fetch_assoc()['total'];

// KPI: pending reservations
$stmt = $conn->prepare("SELECT COUNT(*) AS total FROM reservas WHERE status = 'pendente' AND data_reserva >= ?");
if (!$stmt) die('SQL error (pendentes): ' . $conn->error);
$stmt->bind_param('s', $hoje);
$stmt->execute();
$pendentes = $stmt->get_result()->fetch_assoc()['total'];
$stmt->close();

// ── Calendar: determine month ────────────────────────────────────────
$calMes = max(1, min(12, (int)($_GET['cal_mes'] ?? date('n'))));
$calAno = max(2020, min(2099, (int)($_GET['cal_ano'] ?? date('Y'))));

$calPrimeiroDia  = mktime(0, 0, 0, $calMes, 1, $calAno);
$calDiasNoMes    = (int)date('t', $calPrimeiroDia);
$calDiaSemIni    = (int)date('w', $calPrimeiroDia); // 0=Sun
$calMesNomes     = [
    1 => 'Janeiro', 2 => 'Fevereiro', 3 => 'Março', 4 => 'Abril',
    5 => 'Maio', 6 => 'Junho', 7 => 'Julho', 8 => 'Agosto',
    9 => 'Setembro', 10 => 'Outubro', 11 => 'Novembro', 12 => 'Dezembro',
];

$calMesAnterior = $calMes - 1;
$calAnoAnterior = $calAno;
if ($calMesAnterior < 1) { $calMesAnterior = 12; $calAnoAnterior--; }

$calMesSeguinte = $calMes + 1;
$calAnoSeguinte = $calAno;
if ($calMesSeguinte > 12) { $calMesSeguinte = 1; $calAnoSeguinte++; }

// ── Calendar: fetch reservations for the month ───────────────────────
$calDataIni = sprintf('%04d-%02d-01', $calAno, $calMes);
$calDataFim = sprintf('%04d-%02d-%02d', $calAno, $calMes, $calDiasNoMes);

$stmt = $conn->prepare("
    SELECT r.data_reserva, r.hora_inicio, r.hora_fim, r.assunto, r.status,
           s.nome AS sala_nome, u.nome AS usuario_nome
    FROM reservas r
    JOIN salas s ON s.id = r.sala_id
    JOIN usuarios u ON u.id = r.usuario_id
    WHERE r.data_reserva >= ? AND r.data_reserva <= ?
    ORDER BY r.hora_inicio ASC
");
if (!$stmt) die('SQL error (calendar): ' . $conn->error);
$stmt->bind_param('ss', $calDataIni, $calDataFim);
$stmt->execute();
$calResult = $stmt->get_result();
$stmt->close();

$calReservas = [];
while ($cr = $calResult->fetch_assoc()) {
    $d = $cr['data_reserva'];
    if (!isset($calReservas[$d])) $calReservas[$d] = [];
    $calReservas[$d][] = $cr;
}

// ── Normal reservations table (not generated by recurrence) ──────────
$stmt = $conn->prepare("
    SELECT r.hora_inicio, r.hora_fim, r.assunto, r.status,
           s.nome AS sala_nome, u.nome AS usuario_nome
    FROM reservas r
    JOIN salas s ON s.id = r.sala_id
    JOIN usuarios u ON u.id = r.usuario_id
    WHERE r.data_reserva = ? AND r.status != 'cancelada' AND r.recorrencia_id IS NULL
    ORDER BY r.hora_inicio ASC
");
if (!$stmt) die('SQL error (normais): ' . $conn->error);
$stmt->bind_param('s', $hoje);
$stmt->execute();
$normais = $stmt->get_result();
$stmt->close();

// Recurring reservations materialized for today
$stmt = $conn->prepare("
    SELECT r.hora_inicio, r.hora_fim, r.assunto, r.status,
           s.nome AS sala_nome, u.nome AS usuario_nome, rc.tipo
    FROM reservas r
    JOIN salas s ON s.id = r.sala_id
    JOIN usuarios u ON u.id = r.usuario_id
    JOIN recorrencias rc ON rc.id = r.recorrencia_id
    WHERE r.data_reserva = ? AND r.status != 'cancelada' AND r.recorrencia_id IS NOT NULL
    ORDER BY r.hora_inicio ASC
");
if (!$stmt) die('SQL error (recorrencias hoje): ' . $conn->error);
$stmt->bind_param('s', $hoje);
$stmt->execute();
$recorrencias = $stmt->get_result();
$stmt->close();

$page_title = "Dashboard";
$additional_styles = '
<style>
    /* ── Calendar card ─────────────────────────────────────────── */
    .cal-wrap {
        background: #edeef2;
        border-radius: 16px;
        overflow: hidden;
        box-shadow:
            0 1px 3px rgba(0,0,0,.08),
            0 4px 14px rgba(0,0,0,.06),
            0 12px 32px rgba(0,0,0,.04);
        border: 1px solid #d5d7de;
    }

    /* ── Header bar ────────────────────────────────────────────── */
    .cal-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding: 1.15rem 1.5rem;
        background: #e4e5ec;
        border-bottom: 1px solid #d5d7de;
    }
    .cal-title {
        margin: 0;
        color: #1e1f2b;
        font-weight: 700;
        font-size: 1.15rem;
        letter-spacing: -.01em;
    }
    .cal-title span {
        color: #858896;
        font-weight: 400;
    }
    .cal-nav {
        display: flex;
        align-items: center;
        gap: .5rem;
    }
    .cal-nav .btn-cal {
        background: rgba(255,255,255,.5);
        border: 1px solid #cbcdd6;
        color: #5c5f6e;
        width: 36px;
        height: 36px;
        border-radius: 10px;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        font-size: .8rem;
        transition: all .2s ease;
        text-decoration: none;
    }
    .cal-nav .btn-cal:hover {
        background: rgba(255,255,255,.75);
        color: #1e1f2b;
        border-color: #b8bac5;
        transform: translateY(-1px);
    }
    .cal-header .btn-hoje {
        background: rgba(255,255,255,.5);
        border: 1px solid #cbcdd6;
        color: #5c5f6e;
        border-radius: 10px;
        padding: .4rem .9rem;
        font-size: .76rem;
        font-weight: 600;
        letter-spacing: .02em;
        text-decoration: none;
        transition: all .2s ease;
    }
    .cal-header .btn-hoje:hover {
        background: var(--primary-color);
        color: #fff;
        border-color: var(--primary-color);
        transform: translateY(-1px);
        box-shadow: 0 4px 12px rgba(220,53,69,.25);
    }
    .cal-legend {
        display: flex;
        align-items: center;
        gap: .85rem;
        margin-left: 1rem;
    }
    .cal-legend-item {
        display: flex;
        align-items: center;
        gap: .35rem;
        font-size: .68rem;
        color: #858896;
        font-weight: 500;
    }
    .cal-legend-dot {
        width: 8px;
        height: 8px;
        border-radius: 50%;
    }
    .cal-legend-dot.lg-conf { background: #22c55e; }
    .cal-legend-dot.lg-pend { background: #eab308; }
    .cal-legend-dot.lg-canc { background: #ef4444; opacity: .5; }

    /* ── Grid ──────────────────────────────────────────────────── */
    .cal-grid {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
    }

    /* ── Day-of-week header ────────────────────────────────────── */
    .cal-dow {
        padding: .65rem .25rem;
        text-align: center;
        font-size: .65rem;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 1px;
        color: #858896;
        background: #e7e8ef;
        border-bottom: 1px solid #d5d7de;
    }
    .cal-dow.weekend {
        color: rgba(220,53,69,.55);
    }

    /* ── Day cells ─────────────────────────────────────────────── */
    .cal-day {
        min-height: 110px;
        padding: .5rem;
        border-right: 1px solid #dddee6;
        border-bottom: 1px solid #dddee6;
        position: relative;
        transition: background .25s ease;
        background: #edeef2;
    }
    .cal-day:hover {
        background: #e4e5ec;
    }
    .cal-day.outside {
        background: #e4e5eb;
    }
    .cal-day.outside:hover {
        background: #dddee6;
    }

    /* Day number */
    .cal-day .day-num {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 28px;
        height: 28px;
        border-radius: 9px;
        font-size: .8rem;
        font-weight: 500;
        color: #4b4d5a;
        margin-bottom: 4px;
        transition: all .2s ease;
    }
    .cal-day.outside .day-num {
        color: #a8aab6;
    }
    .cal-day.today {
        background: rgba(220,53,69,.06);
    }
    .cal-day.today .day-num {
        background: var(--primary-color);
        color: #fff;
        font-weight: 700;
        box-shadow: 0 2px 8px rgba(220,53,69,.3), 0 0 16px rgba(220,53,69,.1);
    }

    /* ── Events ────────────────────────────────────────────────── */
    .cal-evt {
        display: flex;
        align-items: baseline;
        gap: 4px;
        padding: 3px 7px 3px 0;
        margin-bottom: 3px;
        border-radius: 6px;
        font-size: .68rem;
        line-height: 1.4;
        color: #2d2f3b;
        cursor: default;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        transition: all .2s ease;
        border-left: 3px solid transparent;
        background: transparent;
    }
    .cal-evt:hover {
        transform: translateX(2px);
    }
    .cal-evt.st-confirmada {
        border-left-color: #22c55e;
        background: rgba(34,197,94,.12);
        color: #15803d;
    }
    .cal-evt.st-confirmada:hover {
        background: rgba(34,197,94,.2);
    }
    .cal-evt.st-pendente {
        border-left-color: #eab308;
        background: rgba(234,179,8,.12);
        color: #92400e;
    }
    .cal-evt.st-pendente:hover {
        background: rgba(234,179,8,.2);
    }
    .cal-evt.st-cancelada {
        border-left-color: rgba(239,68,68,.4);
        background: rgba(239,68,68,.07);
        color: #9ca3af;
        text-decoration: line-through;
    }
    .cal-evt.st-cancelada:hover {
        background: rgba(239,68,68,.12);
        color: #858896;
    }
    .cal-evt .evt-time {
        font-weight: 700;
        font-size: .62rem;
        opacity: .6;
        flex-shrink: 0;
    }
    .cal-evt .evt-title {
        overflow: hidden;
        text-overflow: ellipsis;
        font-weight: 500;
    }
    .cal-evt .evt-user {
        opacity: .4;
        font-size: .58rem;
        flex-shrink: 0;
    }

    /* ── "More" chip ───────────────────────────────────────────── */
    .cal-more {
        display: inline-block;
        padding: 2px 8px;
        margin-top: 2px;
        border-radius: 6px;
        font-size: .64rem;
        font-weight: 600;
        color: #737684;
        background: rgba(0,0,0,.06);
        cursor: pointer;
        transition: all .2s ease;
        letter-spacing: .01em;
    }
    .cal-more:hover {
        background: var(--primary-color);
        color: #fff;
        transform: translateY(-1px);
        box-shadow: 0 3px 8px rgba(220,53,69,.2);
    }

    /* ── Modal ─────────────────────────────────────────────────── */
    #calDayModal .modal-content {
        background: #edeef2;
        border: 1px solid #d5d7de;
        border-radius: 16px;
        color: #1e1f2b;
        box-shadow: 0 24px 60px rgba(0,0,0,.15);
        overflow: hidden;
    }
    #calDayModal .modal-header {
        border-bottom: 1px solid #d5d7de;
        padding: 1.15rem 1.5rem;
    }
    #calDayModal .modal-title {
        font-weight: 700;
        font-size: 1rem;
        letter-spacing: -.01em;
        color: #1e1f2b;
    }
    #calDayModal .btn-close {
        opacity: .4;
        transition: opacity .2s;
    }
    #calDayModal .btn-close:hover { opacity: .8; }
    #calDayModal .modal-body {
        padding: 1.25rem 1.5rem;
    }
    #calDayModal .modal-body .cal-evt {
        white-space: normal;
        margin-bottom: 8px;
        padding: 8px 10px;
        font-size: .78rem;
        border-radius: 8px;
        border-left-width: 4px;
    }
    #calDayModal .modal-body .cal-evt .evt-time {
        font-size: .7rem;
    }
    #calDayModal .modal-body .cal-evt .evt-user {
        font-size: .68rem;
    }

    /* ── Responsive ────────────────────────────────────────────── */
    @media (max-width: 1199px) {
        .cal-legend { display: none; }
    }
    @media (max-width: 991px) {
        .cal-day { min-height: 88px; padding: .4rem; }
        .cal-evt { font-size: .62rem; }
        .cal-evt .evt-user { display: none; }
        .cal-day .day-num { width: 26px; height: 26px; font-size: .75rem; border-radius: 8px; }
    }
    @media (max-width: 767px) {
        .cal-header { padding: .9rem 1rem; flex-wrap: wrap; gap: .5rem; }
        .cal-title { font-size: 1rem; }
        .cal-day { min-height: 70px; padding: .3rem; }
        .cal-day .day-num { width: 24px; height: 24px; font-size: .72rem; margin-bottom: 2px; }
        .cal-evt { font-size: .58rem; padding: 2px 5px 2px 0; margin-bottom: 2px; border-left-width: 2px; }
        .cal-evt .evt-time { font-size: .55rem; }
        .cal-more { font-size: .58rem; padding: 1px 6px; }
        .cal-dow { font-size: .58rem; padding: .5rem .15rem; letter-spacing: .5px; }
    }
    @media (max-width: 575px) {
        .cal-wrap { border-radius: 12px; }
        .cal-day { min-height: 56px; padding: .2rem; }
        .cal-day .day-num { width: 22px; height: 22px; font-size: .68rem; border-radius: 6px; }
        .cal-evt .evt-title { display: none; }
        .cal-evt { gap: 0; padding: 2px 4px; border-radius: 4px; border-left-width: 2px; }
        .cal-evt .evt-time { font-size: .54rem; opacity: 1; }
        .cal-nav .btn-cal { width: 32px; height: 32px; border-radius: 8px; }
        .cal-header .btn-hoje { padding: .3rem .65rem; font-size: .7rem; }
    }
</style>';

require_once 'includes/header.php';
require_once 'includes/sidebar.php';
?>

<!-- Main Content -->
<div class="main-content">
    <!-- Header -->
    <div class="header d-flex justify-content-between align-items-center">
        <div>
            <button class="btn btn-outline-secondary d-md-none me-3" id="sidebarToggle">
                <i class="bi bi-list"></i>
            </button>
            <h4 class="mb-0">Dashboard</h4>
            <small class="text-muted">Visão geral do sistema</small>
        </div>
        <div class="dropdown">
            <button class="btn btn-outline-secondary dropdown-toggle d-flex align-items-center" type="button" data-bs-toggle="dropdown">
                <?php if (!empty($user['foto']) && file_exists(__DIR__ . '/' . $user['foto'])): ?>
                    <img src="<?php echo htmlspecialchars($user['foto']); ?>" alt="" class="rounded-circle me-2" style="width:40px;height:40px;object-fit:cover;">
                <?php else: ?>
                    <i class="bi bi-person-circle me-2" style="font-size:1.5rem;"></i>
                <?php endif; ?>
                <?php echo htmlspecialchars($user['nome']); ?>
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#"><i class="bi bi-person me-2"></i>Perfil</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="logout.php"><i class="bi bi-box-arrow-right me-2"></i>Sair</a></li>
            </ul>
        </div>
    </div>

    <!-- Content -->
    <div class="container-fluid px-4">
        <?php renderFlash(); ?>

        <!-- Stats Cards -->
        <div class="row mb-4">
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="stat-card">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <div class="text-muted small">Reservas Hoje</div>
                            <div class="h4 mb-0"><?php echo $reservasHoje; ?></div>
                        </div>
                        <div class="stat-icon">
                            <i class="bi bi-calendar-day"></i>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="stat-card">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <div class="text-muted small">Salas Ativas</div>
                            <div class="h4 mb-0"><?php echo $salasAtivas; ?></div>
                        </div>
                        <div class="stat-icon">
                            <i class="bi bi-door-open"></i>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="stat-card">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <div class="text-muted small">Usuários Ativos</div>
                            <div class="h4 mb-0"><?php echo $usersAtivos; ?></div>
                        </div>
                        <div class="stat-icon">
                            <i class="bi bi-people"></i>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="stat-card">
                    <div class="d-flex justify-content-between align-items-center">
                        <div>
                            <div class="text-muted small">Reservas Pendentes</div>
                            <div class="h4 mb-0"><?php echo $pendentes; ?></div>
                        </div>
                        <div class="stat-icon">
                            <i class="bi bi-clock-history"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- ══════ Calendar Section ══════ -->
        <div class="row mb-4">
            <div class="col-12">
                <div class="cal-wrap">
                    <div class="cal-header">
                        <div class="d-flex align-items-center gap-3">
                            <div class="cal-nav">
                                <a href="?cal_mes=<?php echo $calMesAnterior; ?>&cal_ano=<?php echo $calAnoAnterior; ?>" class="btn-cal" title="Mês anterior"><i class="bi bi-chevron-left"></i></a>
                                <a href="?cal_mes=<?php echo $calMesSeguinte; ?>&cal_ano=<?php echo $calAnoSeguinte; ?>" class="btn-cal" title="Próximo mês"><i class="bi bi-chevron-right"></i></a>
                            </div>
                            <h5 class="cal-title"><?php echo $calMesNomes[$calMes]; ?> <span><?php echo $calAno; ?></span></h5>
                            <div class="cal-legend">
                                <div class="cal-legend-item"><span class="cal-legend-dot lg-conf"></span>Confirmada</div>
                                <div class="cal-legend-item"><span class="cal-legend-dot lg-pend"></span>Pendente</div>
                                <div class="cal-legend-item"><span class="cal-legend-dot lg-canc"></span>Cancelada</div>
                            </div>
                        </div>
                        <a href="?cal_mes=<?php echo date('n'); ?>&cal_ano=<?php echo date('Y'); ?>" class="btn-hoje"><i class="bi bi-circle-fill me-1" style="font-size:.4rem;vertical-align:middle"></i>Hoje</a>
                    </div>

                    <div class="cal-grid">
                        <?php
                        $dowLabels = ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'];
                        foreach ($dowLabels as $idx => $dl):
                            $wkend = ($idx === 0 || $idx === 6) ? ' weekend' : '';
                        ?>
                            <div class="cal-dow<?php echo $wkend; ?>"><?php echo $dl; ?></div>
                        <?php endforeach; ?>

                        <?php
                        $prevMonthDays = (int)date('t', mktime(0, 0, 0, $calMes - 1, 1, $calAno));
                        for ($i = 0; $i < $calDiaSemIni; $i++):
                            $pDay = $prevMonthDays - $calDiaSemIni + $i + 1;
                        ?>
                            <div class="cal-day outside"><span class="day-num"><?php echo $pDay; ?></span></div>
                        <?php endfor; ?>

                        <?php
                        $calMaxVisible = 3;
                        for ($d = 1; $d <= $calDiasNoMes; $d++):
                            $dateStr  = sprintf('%04d-%02d-%02d', $calAno, $calMes, $d);
                            $isToday  = ($dateStr === $hoje);
                            $dayEvts  = $calReservas[$dateStr] ?? [];
                            $evtCount = count($dayEvts);
                        ?>
                            <div class="cal-day<?php echo $isToday ? ' today' : ''; ?>"<?php if ($evtCount > 0) echo ' onclick="calShowDay(\'' . $dateStr . '\')" style="cursor:pointer"'; ?>>
                                <span class="day-num"><?php echo $d; ?></span>
                                <?php
                                $shown = 0;
                                foreach ($dayEvts as $ev):
                                    if ($shown >= $calMaxVisible) break;
                                    $shown++;
                                    $stClass = 'st-' . $ev['status'];
                                ?>
                                    <div class="cal-evt <?php echo $stClass; ?>" title="<?php echo htmlspecialchars($ev['assunto'] . ' — ' . $ev['sala_nome'] . ' (' . $ev['usuario_nome'] . ')'); ?>">
                                        <span class="evt-time"><?php echo substr($ev['hora_inicio'], 0, 5); ?></span>
                                        <span class="evt-title"><?php echo htmlspecialchars($ev['assunto']); ?></span>
                                        <span class="evt-user">&middot; <?php echo htmlspecialchars($ev['usuario_nome']); ?></span>
                                    </div>
                                <?php endforeach; ?>
                                <?php if ($evtCount > $calMaxVisible): ?>
                                    <span class="cal-more">+<?php echo $evtCount - $calMaxVisible; ?> mais</span>
                                <?php endif; ?>
                            </div>
                        <?php endfor; ?>

                        <?php
                        $totalCells  = $calDiaSemIni + $calDiasNoMes;
                        $trailingCells = (7 - ($totalCells % 7)) % 7;
                        for ($i = 1; $i <= $trailingCells; $i++):
                        ?>
                            <div class="cal-day outside"><span class="day-num"><?php echo $i; ?></span></div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>
        </div>

        <!-- Quick Actions & Recent Bookings -->
        <div class="row">
            <div class="col-lg-4 mb-4">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Ações Rápidas</h5>
                    </div>
                    <div class="card-body">
                        <div class="d-grid gap-2">
                            <a href="nova_reserva.php" class="btn btn-primary">
                                <i class="bi bi-plus-circle me-2"></i>Nova Reserva
                            </a>
                            <a href="salas.php" class="btn btn-outline-primary">
                                <i class="bi bi-door-open me-2"></i>Gerir Salas
                            </a>
                            <?php if (isAdmin()): ?>
                            <a href="usuarios.php" class="btn btn-outline-primary">
                                <i class="bi bi-people me-2"></i>Gerir Usuários
                            </a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-lg-8 mb-4">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="card-title mb-0"><i class="bi bi-calendar-event me-2"></i>Reservas Normais — Hoje <small class="text-muted fw-normal"><?php echo date('d/m/Y'); ?></small></h5>
                        <a href="reservas.php" class="btn btn-sm btn-outline-primary">Ver Todas</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Sala</th>
                                        <th>Horário</th>
                                        <th>Assunto</th>
                                        <th>Responsável</th>
                                        <th>Estado</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if ($normais->num_rows === 0): ?>
                                        <tr><td colspan="5" class="text-center text-muted">Sem reservas normais para hoje</td></tr>
                                    <?php else: ?>
                                        <?php while ($row = $normais->fetch_assoc()): ?>
                                        <tr>
                                            <td><?php echo htmlspecialchars($row['sala_nome']); ?></td>
                                            <td><?php echo substr($row['hora_inicio'], 0, 5) . ' - ' . substr($row['hora_fim'], 0, 5); ?></td>
                                            <td><?php echo htmlspecialchars($row['assunto']); ?></td>
                                            <td><?php echo htmlspecialchars($row['usuario_nome']); ?></td>
                                            <td>
                                                <?php
                                                $badge = match($row['status']) {
                                                    'confirmada' => 'bg-success',
                                                    'pendente'   => 'bg-warning',
                                                    'cancelada'  => 'bg-danger',
                                                    default      => 'bg-secondary',
                                                };
                                                ?>
                                                <span class="badge <?php echo $badge; ?>"><?php echo ucfirst($row['status']); ?></span>
                                            </td>
                                        </tr>
                                        <?php endwhile; ?>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Recurring Reservations -->
        <div class="row">
            <div class="col-12 mb-4">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="card-title mb-0"><i class="bi bi-arrow-repeat me-2"></i>Reservas Recorrentes — Hoje <small class="text-muted fw-normal"><?php echo date('d/m/Y'); ?></small></h5>
                        <a href="recorrencias.php" class="btn btn-sm btn-outline-primary">Ver Todas</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Sala</th>
                                        <th>Tipo</th>
                                        <th>Horário</th>
                                        <th>Assunto</th>
                                        <th>Responsável</th>
                                        <th>Estado</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if ($recorrencias->num_rows === 0): ?>
                                        <tr><td colspan="6" class="text-center text-muted">Sem reservas recorrentes para hoje</td></tr>
                                    <?php else: ?>
                                        <?php while ($rc = $recorrencias->fetch_assoc()):
                                            $badge = match($rc['status']) {
                                                'confirmada' => 'bg-success',
                                                'pendente'   => 'bg-warning',
                                                default      => 'bg-secondary',
                                            };
                                        ?>
                                        <tr>
                                            <td><?php echo htmlspecialchars($rc['sala_nome']); ?></td>
                                            <td><span class="badge bg-info"><?php echo ucfirst($rc['tipo']); ?></span></td>
                                            <td><?php echo substr($rc['hora_inicio'], 0, 5) . ' - ' . substr($rc['hora_fim'], 0, 5); ?></td>
                                            <td><?php echo htmlspecialchars($rc['assunto']); ?></td>
                                            <td><?php echo htmlspecialchars($rc['usuario_nome']); ?></td>
                                            <td><span class="badge <?php echo $badge; ?>"><?php echo ucfirst($rc['status']); ?></span></td>
                                        </tr>
                                        <?php endwhile; ?>
                                    <?php endif; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Calendar Day Modal -->
<div class="modal fade" id="calDayModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="calDayModalTitle">Reservas</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
            </div>
            <div class="modal-body" id="calDayModalBody"></div>
        </div>
    </div>
</div>

<?php
// Encode all month events as JSON so JS can render them inside the modal
$calAllJson = [];
foreach ($calReservas as $date => $evts) {
    foreach ($evts as $ev) {
        $calAllJson[] = [
            'date'    => $date,
            'inicio'  => substr($ev['hora_inicio'], 0, 5),
            'fim'     => substr($ev['hora_fim'], 0, 5),
            'assunto' => $ev['assunto'],
            'sala'    => $ev['sala_nome'],
            'user'    => $ev['usuario_nome'],
            'status'  => $ev['status'],
        ];
    }
}

$additional_scripts = '
<script>
var calEvents = ' . json_encode($calAllJson, JSON_HEX_TAG | JSON_HEX_APOS) . ';
var _calModal = null;

function calShowDay(dateStr) {
    var evts = calEvents.filter(function(e) { return e.date === dateStr; });
    var parts = dateStr.split("-");
    var dayNames = ["Domingo","Segunda-feira","Terça-feira","Quarta-feira","Quinta-feira","Sexta-feira","Sábado"];
    var dt = new Date(parseInt(parts[0]), parseInt(parts[1])-1, parseInt(parts[2]));
    var title = dayNames[dt.getDay()] + ", " + parts[2] + "/" + parts[1] + "/" + parts[0];
    document.getElementById("calDayModalTitle").textContent = title;

    var html = "";
    if (evts.length === 0) {
        html = "<p style=\"color:#858896;text-align:center;padding:1rem 0\">Sem reservas neste dia.</p>";
    } else {
        html = "<div style=\"display:flex;flex-direction:column;gap:4px\">";
        evts.forEach(function(ev) {
            var cls = "st-" + ev.status;
            html += "<div class=\"cal-evt " + cls + "\">"
                  + "<span class=\"evt-time\">" + ev.inicio + " – " + ev.fim + "</span> "
                  + "<span class=\"evt-title\">" + escHtml(ev.assunto) + "</span>"
                  + " <span class=\"evt-user\">&middot; " + escHtml(ev.sala) + " &middot; " + escHtml(ev.user) + "</span>"
                  + "</div>";
        });
        html += "</div>";
    }
    document.getElementById("calDayModalBody").innerHTML = html;
    if (!_calModal) _calModal = new bootstrap.Modal(document.getElementById("calDayModal"));
    _calModal.show();
}

function escHtml(t) {
    var d = document.createElement("div");
    d.appendChild(document.createTextNode(t));
    return d.innerHTML;
}
</script>';

require_once 'includes/footer.php';
?>